name: flutter_linkify_example
description: flutter_linkify example
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.0
  flutter_linkify:
    path: ..
  # linkify: ^5.0.0
  # linkify:
  #   path: ../../linkify
    # git:
    #   url: https://github.com/vietstone-ng/linkify.git
    #   ref: 89cf6f3c9fbac9f8a77189effa33dad2e725676f

dependency_overrides:
  linkify:
    path: ../../linkify

flutter:
  uses-material-design: true
