name: flutter_linkify
description: Turns text URLs and emails into clickable inline links in text for Flutter.
version: 6.0.0
homepage: https://github.com/Cretezy/flutter_linkify

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  re_highlight: ^0.0.3
  linkify:
    # path: ../linkify
    git:
      url: https://github.com/vietstone-ng/linkify.git
      ref: 3196671795d16383d3f354431d0c5665226a36c8

dev_dependencies:
  test: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
