name: flutter_linkify
description: Turns text URLs and emails into clickable inline links in text for Flutter.
version: 6.0.0
homepage: https://github.com/Cretezy/flutter_linkify

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  # linkify: ^5.0.0
  flutter_highlighter: ^0.1.1
  highlighter: ^0.1.1
  linkify:
    path: ../linkify

dev_dependencies:
  test: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
